name: pr_equipamentos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # HTTP client for API requests
  http: ^1.1.0
  
  # Camera and image handling
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # UI and utilities
  provider: ^6.1.1
  intl: ^0.18.1
  uuid: ^4.2.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
